name: deploy Image for prod 

on:
  workflow_dispatch:
    inputs:
      admin_approval:
        description: 'Require admin approval'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Update Submodule
        run: |
          git submodule update --remote --merge
  
      - name: Run submodule workflow
        uses: .github/workflow